# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
# https://docs.github.com/en/actions/reference/environment-variables

name: Build and Push Docker Image

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on main branch
      - main
      - master
      # Push events to branches matching refs/heads/releases/10
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:
      - v*
      - v1.*           # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get Branch
      id: branch
      run: echo "git_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_BRANCH

    - name: Check Branch
      run: echo "${{ env.branch }}"

    - name: Get Hash
      id: hash
      run: echo "SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

    - name: Check Hash
      run: echo "${{ env.hash }}"

    - name: Check Hash
      run: echo "${{ SHORT_SHA }}"

  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: echo $SHORT_SHA
      run: echo "${{ SHORT_SHA }}"

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 8

    - name: Shoutrrr on git push
      uses: containrrr/shoutrrr-action@v1
      with:
        url: ${{ secrets.SHOUTRRR_URL }}
        message: '{"msgtype": "text","text": {"content":"pushed commit ${{ steps.short-sha.outputs.sha }}, See changes at ${{ github.event.compare }}."}}'

    - name: Build & push to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: 2mui/ui-market-web
        # tags: ${{ github.sha }}, ${{ steps.docker_meta.outputs.tags }}, latest
        tags: latest, master, ${{ github.sha }}, ${{ steps.short-sha.outputs.sha }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Shoutrrr on docker push
      uses: containrrr/shoutrrr-action@v1
      with:
        url: ${{ secrets.SHOUTRRR_URL }}
        message: '{"msgtype": "text","text": {"content":"pushed image to docker hub, See https://hub.docker.com/r/2mui/ui-market-web"}}'
